language: node_js
node_js:
  - "node"
install:
  - npm install
  - npm run lerna:bootstrap
script:
  - commitlint-travis
  - npm run test
  - npm run deploy
deploy:
  provider: script
  script: publish-preview.sh
  on:
    branch: develop
